HotZone_config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('locations/', include('locations.urls')),
    path('admin/', admin.site.urls),
]

locations/urls.py
from django.urls import path

from . import views

app_name = 'locations'
urlpatterns = [
    path('', views.index, name='index'),
    path('select/<str:query>', views.select, name='select'),
]

locations/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.


class Location(models.Model):
    addressZH = models.CharField(max_length=200)
    nameZH = models.CharField(max_length=200)
    x = models.IntegerField(default=0)
    y = models.IntegerField(default=0)
    nameEN = models.CharField(max_length=200)
    addressEN = models.CharField(max_length=200)

    def __str__(self):
        return self.addressZH

locations/forms.py
from django import forms
from django.forms import ModelForm

from .models import Location


class LocationForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': 'Input location...'}))

    class Meta:
        model = Location
        fields = '__all__'

locations/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.template import loader
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from .forms import *
from .models import Location
import requests
# Create your views here.


def index(request):
    location_list = Location.objects.order_by('-addressZH')[:]
    template = loader.get_template('locations/index.html')
    form = LocationForm()
    context = {
        'location_list': location_list,
        'form': form
    }

    if request.method == "POST":
        query = request.POST.__getitem__('name')
        return HttpResponseRedirect(reverse('locations:select', args=(query,)))

    return HttpResponse(template.render(context, request))


def select(request, query):
    session = requests.Session()
    response = session.get(
        'https://geodata.gov.hk/gs/api/v1.0.0/locationSearch?q='+query)
    select_list = response.json()
    template = loader.get_template('locations/select.html')
    context = {
        'query': query,
        'select_list': select_list,
    }

    if request.method == "POST":
        index = request.POST.get('choice', False)
        if(index):
            selected_choice = select_list[int(index)]
            print(index)
            print(selected_choice)
            new_location = Location(addressZH=selected_choice['addressZH'],
                                    nameZH=selected_choice['nameZH'],
                                    x=selected_choice['x'],
                                    y=selected_choice['y'],
                                    nameEN=selected_choice['nameEN'],
                                    addressEN=selected_choice['addressEN'])
            new_location.save()
            return redirect('/locations/')
        else:
            context = {
                'query': query,
                'select_list': select_list,
                'error_message': "You didn't select a choice. Please select again!",
            }
            return HttpResponse(template.render(context, request))
    return HttpResponse(template.render(context, request))

locations/templates/locations/index.html
<style>
    table {
        width: 100%;
    }

    table,
    th,
    td {
        border: 1px solid black;
        border-collapse: collapse;
    }

    th,
    td {
        padding: 15px;
        text-align: left;
    }
</style>
<h1>HotZone</h1>

<p>Search location:</p>
<form action="{% url 'locations:index'%}" method="post">
    {% csrf_token %}
    {{form.name}}
    <input type="submit" name="Find Location">
</form>

{% if location_list %}
<p>Location list:</p>
<table>
    <tr>
        <th>addressZH</th>
        <th>nameZH</th>
        <th>x</th>
        <th>y</th>
        <th>nameEN</th>
        <th>addressEN</th>
    </tr>
    {% for location in location_list %}
    <tr>
        <td>{{ location.addressZH }}</td>
        <td>{{ location.nameZH }}</td>
        <td>{{ location.x }}</td>
        <td>{{ location.y }}</td>
        <td>{{ location.nameEN }}</td>
        <td>{{ location.addressEN }}</td>
    </tr>
    {% endfor %}
</table>
{% else %}
<p>No location are found.</p>
{% endif %}

locations/templates/locations/select.html
<h1>Select location</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'locations:select' query %}" method="post">
    {% csrf_token %}
    <table>
        {% for location in select_list %}
        <tr>
            <td><input type="radio" name="choice" id="choice{{ forloop.counter0 }}" value="{{ forloop.counter0 }}"></td>
            <td>Name: {{ location.nameEN }}</td>
            <td>Address: {{ location.addressEN }}</td>
        </tr>
        {% endfor %}
    </table>
    <input type="submit" value="Select">
</form>